language: ruby
rvm:
  - 2.6.5

before_script:
  - chmod +x ./script/cibuild

script: ./script/cibuild

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master # test the master branch

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
env:
  global:
  - NOKOGIRI_USE_SYSTER_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl14-openssl-dev

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false