language: ruby
rvm:
  - 2.6.5

before_script:
  - chmod +x ./script/cibuild

script: ./script/cibuild

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master # test the master branch

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
env:
  global:
  - NOKOGIRI_USE_SYSTER_LIBRARIES=true # speeds up installation of html-proofer
    secure: cLpXcVz4UmtEuKGbgc3xCzNEaD8nC/XkEmSOwnjJz1wZLVtyDJOVXFq2FF3R4mffvldn8WckZ7xAUFw/8q0RmbQa0zs5YaYBx3jzlXY60N7E2kSV1sg6hah1LKnVfEKW1sIf3+CJIKLugoacqE96AAHu8XSGL36ovHytSqAXnG5B6alhtH83kkvlNhlRAY0BabX40/JlborITTB7KcdI81CuDlAmbA0gMHiF7fndEoRD+WQiv/ugN7dtAc6/99TT18635RRPhrxMdfRFek3iECBXQMThHVK6BRWOvTZ1dzKGs8kYEFPrfQ9kI1SwNiLrQX48QaJEPPSYQu/rXbpZVcdEYUY/0pOlVJoMlPlPum/3iMP5CwM7neCqRG7WHsjBqiCtvxjI70eNEuyUiOSb+uJhGLe10ABSh5Rac248f5SJkqq/SoABI8KOaRJG9OnM5GQd507J7rSOCNrqzdciZL9I4QDZI08tThgQUbxsZwBuRo88dZj6Wg1SVrM+u1XW75ed7YGds45/iYRX34H+UXFTeYvbHU6Af/xBTLFOCjBrYVeavbmRLpmQeGNJCma1rk/AXGRFHrf6jDkyPgxUCno7YTTRRWSV7SFFQAW6DntqFOK55a2OrB9UWc6pGfS8nMVrN464WSXToqGGjBF2BsWZPbb9KVzpKW13u7SkUNo=

addons:
  apt:
    packages:
    - libcurl14-openssl-dev

sudo: false # route build to the container-based infrastructure for a faster build
cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false